server:
  port: 8081
spring:
  application:
    name: poppopseoul
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppseoul
    username: "root"
    password: "0000"
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop  # option type: create, create-drop, update, validate, none
    show-sql: true
  jwt:
    secret: api-poppopseoul-jwt-authentication-sha256-login-secret-key
    accessTokenExpiration: 900000
    refreshTokenExpiration: 1209600000
swagger:
  server:
    url: http://localhost:8081
logging:
  level:
    com.sm.seoulmate: DEBUG
    com.zaxxer.hikari: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
google:
  oauth:
    client-ids:
      - 222259160589-9s3a5o54ur0ebk8pnvpoch2aj52p8t2m.apps.googleusercontent.com
      - 222259160589-qrilqthr6njluafs3inq3lan0mrikp3u.apps.googleusercontent.com
facebook:
  oauth:
    url: https://graph.facebook.com/me?fields=id,name,email&access_token=
